name: Pylint

on: [push, pull_request]

jobs:
  static-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pylint
          python -m pip install --upgrade isort
          python -m pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          isort $(git ls-files '*.py') --check-only --diff
          pylint $(git ls-files '*.py')
